services:
  # The PostgreSQL Database Service with pgvector
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    environment:
      # These will be read from environment variables
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # The RAG Application Service
  app:
    container_name: rag_app
    build: .
    depends_on:
      - db
    environment:
      # This connection string is now also built from the secrets
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    restart: unless-stopped

  # The Nginx Reverse Proxy Service
  nginx:
    image: nginx:1.25-alpine
    container_name: rag_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
