services:
  # The PostgreSQL Database Service with pgvector
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    environment:
      - POSTGRES_USER=raguser
      - POSTGRES_PASSWORD=ragpassword
      - POSTGRES_DB=ragdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # The RAG Application Service (no longer exposes ports directly)
  app:
    container_name: rag_app
    build: .
    # Note: The ports section is removed from here.
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://raguser:ragpassword@db:5432/ragdb
    restart: unless-stopped

  # NEW: The Nginx Reverse Proxy Service
  nginx:
    image: nginx:1.25-alpine
    container_name: rag_proxy
    ports:
      # Map port 80 of the host (EC2 instance) to port 80 of the nginx container.
      - "80:80"
    volumes:
      # Mount our custom nginx configuration file into the container.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
