# .github/workflows/deploy.yml

name: Deploy RAG App to EC2

on:
  push:
    branches:
      - main-V2

jobs:
  # Job to provision or update infrastructure using Terraform
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    outputs:
      # This output will be used by the next job
      public_ip: ${{ steps.apply.outputs.public_ip }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Must match the region in your .tf file

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve
          # Extract the public IP output from Terraform and set it for the next job
          echo "public_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT

  # Job to deploy the application to the newly created EC2 instance
  deploy:
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    # This job depends on the terraform job completing successfully
    needs: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
            
      - name: Copy Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ needs.terraform.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "."
          target: "~/rag-app"
          
      - name: Deploy and Run Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.terraform.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          request_pty: true
          script: |
            cd ~/rag-app
       
             # Ensure Docker is running (add a check for readiness)
            echo "Checking if Docker is installed and running..."
            if ! sudo systemctl is-active --quiet docker; then
             echo "Docker is not running. Attempting to start..."
             sudo systemctl start docker
            fi
            sudo docker --version  # Log Docker version for debugging
      
            # Start only the database service in the background (use 'docker compose')
            echo "Starting database service..."
            sudo docker compose up -d db
      
            # Wait for the database to initialize (increase sleep if needed for reliability)
            echo "Waiting for database to be ready..."
            sleep 30  # Adjusted to 30 seconds; monitor logs to fine-tune
      
            # Run the database migration inside a temporary container
            echo "Running database migration..."
            sudo docker compose run --rm app python migrate_db.py
      
            # Now, bring up the entire application stack, rebuilding if needed
            echo "Starting application..."
            sudo docker compose up --build -d
      
            # Optional: Log container status for verification
            sudo docker compose ps
