# .github/workflows/deploy-lambda.yml

name: Deploy RAG App to AWS Lambda

on:
  push:
    branches:
      - main-V4

jobs:
  deploy-lambda:
    name: 'Deploy to Lambda'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -t ./package
          cp -r ./api ./package/
          cp -r ./public ./package/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Must match the region in your .tf file

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="database_url=${{ secrets.DATABASE_URL }}" \
            -var="hugging_face_api_token=${{ secrets.HUGGING_FACE_API_TOKEN }}"
